version: "3"
name: container-case-explorer-ui
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 19006:19006
    volumes:
      - ../components:/app/components:rw
      - ../assets:/app/assets:rw
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
