
version: "3"

name: container-case-explorer-ui
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 19006:19006
    volumes:
      - ../components:/app/components:ro
      - ../functions:/app/functions:ro
      - ../src:/app/src:ro
      - ../graphql:/app/graphql:ro
      - ../hooks:/app/hooks:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true

