/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateCaselawV4Input = {
  DocSourceId: string,
  SourceDocDate?: string | null,
  ecli: string,
  instance?: string | null,
  alternative_publications?: string | null,
  case_number?: string | null,
  date_added?: string | null,
  date_decision?: string | null,
  date_publication?: string | null,
  display_subtitle?: string | null,
  display_title?: string | null,
  document_id?: string | null,
  document_type?: string | null,
  domains?: string | null,
  ecli_decision?: string | null,
  full_text?: string | null,
  info?: string | null,
  issue_number?: string | null,
  jurisdiction_city?: string | null,
  jurisdiction_country?: string | null,
  language?: string | null,
  legal_provision?: string | null,
  predecessor_successor_cases?: string | null,
  procedure_type?: string | null,
  publication_number?: string | null,
  referenced_legislation_titles?: string | null,
  source?: string | null,
  summary?: string | null,
  target_ecli?: string | null,
  title?: string | null,
  url_entry?: string | null,
  url_publication?: string | null,
};

export type ModelCaselawV4ConditionInput = {
  SourceDocDate?: ModelStringInput | null,
  instance?: ModelStringInput | null,
  alternative_publications?: ModelStringInput | null,
  case_number?: ModelStringInput | null,
  date_added?: ModelStringInput | null,
  date_decision?: ModelStringInput | null,
  date_publication?: ModelStringInput | null,
  display_subtitle?: ModelStringInput | null,
  display_title?: ModelStringInput | null,
  document_id?: ModelStringInput | null,
  document_type?: ModelStringInput | null,
  domains?: ModelStringInput | null,
  ecli_decision?: ModelStringInput | null,
  full_text?: ModelStringInput | null,
  info?: ModelStringInput | null,
  issue_number?: ModelStringInput | null,
  jurisdiction_city?: ModelStringInput | null,
  jurisdiction_country?: ModelStringInput | null,
  language?: ModelStringInput | null,
  legal_provision?: ModelStringInput | null,
  predecessor_successor_cases?: ModelStringInput | null,
  procedure_type?: ModelStringInput | null,
  publication_number?: ModelStringInput | null,
  referenced_legislation_titles?: ModelStringInput | null,
  source?: ModelStringInput | null,
  summary?: ModelStringInput | null,
  target_ecli?: ModelStringInput | null,
  title?: ModelStringInput | null,
  url_entry?: ModelStringInput | null,
  url_publication?: ModelStringInput | null,
  and?: Array< ModelCaselawV4ConditionInput | null > | null,
  or?: Array< ModelCaselawV4ConditionInput | null > | null,
  not?: ModelCaselawV4ConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type CaselawV4 = {
  __typename: "CaselawV4",
  DocSourceId?: string,
  SourceDocDate?: string | null,
  ecli?: string,
  instance?: string | null,
  alternative_publications?: string | null,
  case_number?: string | null,
  date_added?: string | null,
  date_decision?: string | null,
  date_publication?: string | null,
  display_subtitle?: string | null,
  display_title?: string | null,
  document_id?: string | null,
  document_type?: string | null,
  domains?: string | null,
  ecli_decision?: string | null,
  full_text?: string | null,
  info?: string | null,
  issue_number?: string | null,
  jurisdiction_city?: string | null,
  jurisdiction_country?: string | null,
  language?: string | null,
  legal_provision?: string | null,
  predecessor_successor_cases?: string | null,
  procedure_type?: string | null,
  publication_number?: string | null,
  referenced_legislation_titles?: string | null,
  source?: string | null,
  summary?: string | null,
  target_ecli?: string | null,
  title?: string | null,
  url_entry?: string | null,
  url_publication?: string | null,
  createdAt?: string,
  updatedAt?: string,
};

export type UpdateCaselawV4Input = {
  DocSourceId: string,
  SourceDocDate?: string | null,
  ecli: string,
  instance?: string | null,
  alternative_publications?: string | null,
  case_number?: string | null,
  date_added?: string | null,
  date_decision?: string | null,
  date_publication?: string | null,
  display_subtitle?: string | null,
  display_title?: string | null,
  document_id?: string | null,
  document_type?: string | null,
  domains?: string | null,
  ecli_decision?: string | null,
  full_text?: string | null,
  info?: string | null,
  issue_number?: string | null,
  jurisdiction_city?: string | null,
  jurisdiction_country?: string | null,
  language?: string | null,
  legal_provision?: string | null,
  predecessor_successor_cases?: string | null,
  procedure_type?: string | null,
  publication_number?: string | null,
  referenced_legislation_titles?: string | null,
  source?: string | null,
  summary?: string | null,
  target_ecli?: string | null,
  title?: string | null,
  url_entry?: string | null,
  url_publication?: string | null,
};

export type DeleteCaselawV4Input = {
  ecli: string,
  DocSourceId: string,
};

export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelCaselawV4FilterInput = {
  DocSourceId?: ModelStringInput | null,
  SourceDocDate?: ModelStringInput | null,
  ecli?: ModelStringInput | null,
  instance?: ModelStringInput | null,
  alternative_publications?: ModelStringInput | null,
  case_number?: ModelStringInput | null,
  date_added?: ModelStringInput | null,
  date_decision?: ModelStringInput | null,
  date_publication?: ModelStringInput | null,
  display_subtitle?: ModelStringInput | null,
  display_title?: ModelStringInput | null,
  document_id?: ModelStringInput | null,
  document_type?: ModelStringInput | null,
  domains?: ModelStringInput | null,
  ecli_decision?: ModelStringInput | null,
  full_text?: ModelStringInput | null,
  info?: ModelStringInput | null,
  issue_number?: ModelStringInput | null,
  jurisdiction_city?: ModelStringInput | null,
  jurisdiction_country?: ModelStringInput | null,
  language?: ModelStringInput | null,
  legal_provision?: ModelStringInput | null,
  predecessor_successor_cases?: ModelStringInput | null,
  procedure_type?: ModelStringInput | null,
  publication_number?: ModelStringInput | null,
  referenced_legislation_titles?: ModelStringInput | null,
  source?: ModelStringInput | null,
  summary?: ModelStringInput | null,
  target_ecli?: ModelStringInput | null,
  title?: ModelStringInput | null,
  url_entry?: ModelStringInput | null,
  url_publication?: ModelStringInput | null,
  and?: Array< ModelCaselawV4FilterInput | null > | null,
  or?: Array< ModelCaselawV4FilterInput | null > | null,
  not?: ModelCaselawV4FilterInput | null,
};

export type ModelCaselawV4Connection = {
  __typename: "ModelCaselawV4Connection",
  items?:  Array<CaselawV4 | null > | null,
  nextToken?: string | null,
};

export type CreateCaselawV4MutationVariables = {
  input?: CreateCaselawV4Input,
  condition?: ModelCaselawV4ConditionInput | null,
};

export type CreateCaselawV4Mutation = {
  createCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateCaselawV4MutationVariables = {
  input?: UpdateCaselawV4Input,
  condition?: ModelCaselawV4ConditionInput | null,
};

export type UpdateCaselawV4Mutation = {
  updateCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteCaselawV4MutationVariables = {
  input?: DeleteCaselawV4Input,
  condition?: ModelCaselawV4ConditionInput | null,
};

export type DeleteCaselawV4Mutation = {
  deleteCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type QueryByEcliQueryVariables = {
  ecli?: string,
  DocSourceId?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelCaselawV4FilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type QueryByEcliQuery = {
  queryByEcli?:  {
    __typename: "ModelCaselawV4Connection",
    items?:  Array< {
      __typename: "CaselawV4",
      DocSourceId: string,
      SourceDocDate?: string | null,
      ecli: string,
      instance?: string | null,
      alternative_publications?: string | null,
      case_number?: string | null,
      date_added?: string | null,
      date_decision?: string | null,
      date_publication?: string | null,
      display_subtitle?: string | null,
      display_title?: string | null,
      document_id?: string | null,
      document_type?: string | null,
      domains?: string | null,
      ecli_decision?: string | null,
      full_text?: string | null,
      info?: string | null,
      issue_number?: string | null,
      jurisdiction_city?: string | null,
      jurisdiction_country?: string | null,
      language?: string | null,
      legal_provision?: string | null,
      predecessor_successor_cases?: string | null,
      procedure_type?: string | null,
      publication_number?: string | null,
      referenced_legislation_titles?: string | null,
      source?: string | null,
      summary?: string | null,
      target_ecli?: string | null,
      title?: string | null,
      url_entry?: string | null,
      url_publication?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type GetCaselawV4QueryVariables = {
  ecli?: string,
  DocSourceId?: string,
};

export type GetCaselawV4Query = {
  getCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListCaselawV4sQueryVariables = {
  ecli?: string | null,
  DocSourceId?: ModelStringKeyConditionInput | null,
  filter?: ModelCaselawV4FilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  sortDirection?: ModelSortDirection | null,
};

export type ListCaselawV4sQuery = {
  listCaselawV4s?:  {
    __typename: "ModelCaselawV4Connection",
    items?:  Array< {
      __typename: "CaselawV4",
      DocSourceId: string,
      SourceDocDate?: string | null,
      ecli: string,
      instance?: string | null,
      alternative_publications?: string | null,
      case_number?: string | null,
      date_added?: string | null,
      date_decision?: string | null,
      date_publication?: string | null,
      display_subtitle?: string | null,
      display_title?: string | null,
      document_id?: string | null,
      document_type?: string | null,
      domains?: string | null,
      ecli_decision?: string | null,
      full_text?: string | null,
      info?: string | null,
      issue_number?: string | null,
      jurisdiction_city?: string | null,
      jurisdiction_country?: string | null,
      language?: string | null,
      legal_provision?: string | null,
      predecessor_successor_cases?: string | null,
      procedure_type?: string | null,
      publication_number?: string | null,
      referenced_legislation_titles?: string | null,
      source?: string | null,
      summary?: string | null,
      target_ecli?: string | null,
      title?: string | null,
      url_entry?: string | null,
      url_publication?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type QueryByDocSourceIdQueryVariables = {
  DocSourceId?: string | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelCaselawV4FilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type QueryByDocSourceIdQuery = {
  queryByDocSourceId?:  {
    __typename: "ModelCaselawV4Connection",
    items?:  Array< {
      __typename: "CaselawV4",
      DocSourceId: string,
      SourceDocDate?: string | null,
      ecli: string,
      instance?: string | null,
      alternative_publications?: string | null,
      case_number?: string | null,
      date_added?: string | null,
      date_decision?: string | null,
      date_publication?: string | null,
      display_subtitle?: string | null,
      display_title?: string | null,
      document_id?: string | null,
      document_type?: string | null,
      domains?: string | null,
      ecli_decision?: string | null,
      full_text?: string | null,
      info?: string | null,
      issue_number?: string | null,
      jurisdiction_city?: string | null,
      jurisdiction_country?: string | null,
      language?: string | null,
      legal_provision?: string | null,
      predecessor_successor_cases?: string | null,
      procedure_type?: string | null,
      publication_number?: string | null,
      referenced_legislation_titles?: string | null,
      source?: string | null,
      summary?: string | null,
      target_ecli?: string | null,
      title?: string | null,
      url_entry?: string | null,
      url_publication?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type QueryByInstanceQueryVariables = {
  instance?: string | null,
  SourceDocDate?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelCaselawV4FilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type QueryByInstanceQuery = {
  queryByInstance?:  {
    __typename: "ModelCaselawV4Connection",
    items?:  Array< {
      __typename: "CaselawV4",
      DocSourceId: string,
      SourceDocDate?: string | null,
      ecli: string,
      instance?: string | null,
      alternative_publications?: string | null,
      case_number?: string | null,
      date_added?: string | null,
      date_decision?: string | null,
      date_publication?: string | null,
      display_subtitle?: string | null,
      display_title?: string | null,
      document_id?: string | null,
      document_type?: string | null,
      domains?: string | null,
      ecli_decision?: string | null,
      full_text?: string | null,
      info?: string | null,
      issue_number?: string | null,
      jurisdiction_city?: string | null,
      jurisdiction_country?: string | null,
      language?: string | null,
      legal_provision?: string | null,
      predecessor_successor_cases?: string | null,
      procedure_type?: string | null,
      publication_number?: string | null,
      referenced_legislation_titles?: string | null,
      source?: string | null,
      summary?: string | null,
      target_ecli?: string | null,
      title?: string | null,
      url_entry?: string | null,
      url_publication?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnCreateCaselawV4Subscription = {
  onCreateCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateCaselawV4Subscription = {
  onUpdateCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteCaselawV4Subscription = {
  onDeleteCaselawV4?:  {
    __typename: "CaselawV4",
    DocSourceId: string,
    SourceDocDate?: string | null,
    ecli: string,
    instance?: string | null,
    alternative_publications?: string | null,
    case_number?: string | null,
    date_added?: string | null,
    date_decision?: string | null,
    date_publication?: string | null,
    display_subtitle?: string | null,
    display_title?: string | null,
    document_id?: string | null,
    document_type?: string | null,
    domains?: string | null,
    ecli_decision?: string | null,
    full_text?: string | null,
    info?: string | null,
    issue_number?: string | null,
    jurisdiction_city?: string | null,
    jurisdiction_country?: string | null,
    language?: string | null,
    legal_provision?: string | null,
    predecessor_successor_cases?: string | null,
    procedure_type?: string | null,
    publication_number?: string | null,
    referenced_legislation_titles?: string | null,
    source?: string | null,
    summary?: string | null,
    target_ecli?: string | null,
    title?: string | null,
    url_entry?: string | null,
    url_publication?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
