"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
exports.__esModule = true;
exports.giveMeAllTheData = "\n  query GiveMeAllTheData(\n    $DataSources: [String]\n    $Keywords: [String]\n    $Articles: [String]\n    $Eclis: [String]\n    $DegreesSources: Int\n    $DegreesTargets: Int\n    $DateStart: String\n    $DateEnd: String\n    $Instances: [String]\n    $Domains: [String]\n    $Doctypes: [String]\n    $LiPermission: Boolean\n  ) {\n    giveMeAllTheData(\n      DataSources: $DataSources\n      Keywords: $Keywords\n      Articles: $Articles\n      Eclis: $Eclis\n      DegreesSources: $DegreesSources\n      DegreesTargets: $DegreesTargets\n      DateStart: $DateStart\n      DateEnd: $DateEnd\n      Instances: $Instances\n      Domains: $Domains\n      Doctypes: $Doctypes\n      LiPermission: $LiPermission\n    ) {\n      nodes {\n        id\n        data\n      }\n      edges {\n        id\n        source\n        target\n        data\n      }\n    }\n  }\n";
exports.getCaselawV4 = "\n  query GetCaselawV4($ecli: String!, $DocSourceId: String!) {\n    getCaselawV4(ecli: $ecli, DocSourceId: $DocSourceId) {\n      DocSourceId\n      SourceDocDate\n      ecli\n      instance\n      instance_li\n      extracted_from\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.listCaselawV4s = "\n  query ListCaselawV4s(\n    $ecli: String\n    $DocSourceId: ModelStringKeyConditionInput\n    $filter: ModelCaselawV4FilterInput\n    $limit: Int\n    $nextToken: String\n    $sortDirection: ModelSortDirection\n  ) {\n    listCaselawV4s(\n      ecli: $ecli\n      DocSourceId: $DocSourceId\n      filter: $filter\n      limit: $limit\n      nextToken: $nextToken\n      sortDirection: $sortDirection\n    ) {\n      items {\n        DocSourceId\n        SourceDocDate\n        ecli\n        instance\n        instance_li\n        extracted_from\n        createdAt\n        updatedAt\n      }\n      nextToken\n    }\n  }\n";
exports.queryByDocSourceId = "\n  query QueryByDocSourceId(\n    $DocSourceId: String\n    $extracted_from: ModelStringKeyConditionInput\n    $sortDirection: ModelSortDirection\n    $filter: ModelCaselawV4FilterInput\n    $limit: Int\n    $nextToken: String\n  ) {\n    queryByDocSourceId(\n      DocSourceId: $DocSourceId\n      extracted_from: $extracted_from\n      sortDirection: $sortDirection\n      filter: $filter\n      limit: $limit\n      nextToken: $nextToken\n    ) {\n      items {\n        DocSourceId\n        SourceDocDate\n        ecli\n        instance\n        instance_li\n        extracted_from\n        createdAt\n        updatedAt\n      }\n      nextToken\n    }\n  }\n";
exports.queryByInstance = "\n  query QueryByInstance(\n    $instance: String\n    $SourceDocDate: ModelStringKeyConditionInput\n    $sortDirection: ModelSortDirection\n    $filter: ModelCaselawV4FilterInput\n    $limit: Int\n    $nextToken: String\n  ) {\n    queryByInstance(\n      instance: $instance\n      SourceDocDate: $SourceDocDate\n      sortDirection: $sortDirection\n      filter: $filter\n      limit: $limit\n      nextToken: $nextToken\n    ) {\n      items {\n        DocSourceId\n        SourceDocDate\n        ecli\n        instance\n        instance_li\n        extracted_from\n        createdAt\n        updatedAt\n      }\n      nextToken\n    }\n  }\n";
exports.queryByInstanceLi = "\n  query QueryByInstanceLi(\n    $instance_li: String\n    $SourceDocDate: ModelStringKeyConditionInput\n    $sortDirection: ModelSortDirection\n    $filter: ModelCaselawV4FilterInput\n    $limit: Int\n    $nextToken: String\n  ) {\n    queryByInstanceLi(\n      instance_li: $instance_li\n      SourceDocDate: $SourceDocDate\n      sortDirection: $sortDirection\n      filter: $filter\n      limit: $limit\n      nextToken: $nextToken\n    ) {\n      items {\n        DocSourceId\n        SourceDocDate\n        ecli\n        instance\n        instance_li\n        extracted_from\n        createdAt\n        updatedAt\n      }\n      nextToken\n    }\n  }\n";
exports.searchCaselawV4s = "\n  query SearchCaselawV4s(\n    $filter: SearchableCaselawV4FilterInput\n    $sort: SearchableCaselawV4SortInput\n    $limit: Int\n    $nextToken: String\n    $from: Int\n  ) {\n    searchCaselawV4s(\n      filter: $filter\n      sort: $sort\n      limit: $limit\n      nextToken: $nextToken\n      from: $from\n    ) {\n      items {\n        DocSourceId\n        SourceDocDate\n        ecli\n        instance\n        instance_li\n        extracted_from\n        createdAt\n        updatedAt\n      }\n      nextToken\n      total\n    }\n  }\n";
